// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoyO85gFM6flW_5CqPVJQUwJH6vJKhJ7M',
    appId: '1:936777913875:web:65f9b5e64e31dcc5dd91e6',
    messagingSenderId: '936777913875',
    projectId: 'shop-f0958',
    authDomain: 'shop-f0958.firebaseapp.com',
    storageBucket: 'shop-f0958.firebasestorage.app',
    measurementId: 'G-2YM6YNNCB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALQnTiR8mnuNiVYjZc1v4xIu9G0foFLjA',
    appId: '1:936777913875:android:d6bdf439f1203bb9dd91e6',
    messagingSenderId: '936777913875',
    projectId: 'shop-f0958',
    storageBucket: 'shop-f0958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIkvBldij6Qe9mtCk7AKUrkpq3WhPPe9Y',
    appId: '1:936777913875:ios:e21f90aa74929605dd91e6',
    messagingSenderId: '936777913875',
    projectId: 'shop-f0958',
    storageBucket: 'shop-f0958.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIkvBldij6Qe9mtCk7AKUrkpq3WhPPe9Y',
    appId: '1:936777913875:ios:e21f90aa74929605dd91e6',
    messagingSenderId: '936777913875',
    projectId: 'shop-f0958',
    storageBucket: 'shop-f0958.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoyO85gFM6flW_5CqPVJQUwJH6vJKhJ7M',
    appId: '1:936777913875:web:fa45f4a5faa2b3d6dd91e6',
    messagingSenderId: '936777913875',
    projectId: 'shop-f0958',
    authDomain: 'shop-f0958.firebaseapp.com',
    storageBucket: 'shop-f0958.firebasestorage.app',
    measurementId: 'G-LXKG1MBK31',
  );
}
